export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
export const FILTER_ITEMS = 'FILTER_ITEMS';
export const DELETE_ITEM = 'DELETE_ITEM';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_LOADING = 'FETCH_DATA_LOADING';
export const SHOW_ALERT = 'SHOW_ALERT';
export const FETCH_DATA = 'FETCH_DATA';
export const SHOW_DATA_ALERT = 'SHOW_DATA_ALERT';